### ISSUE TITLE
Question for the code?

### ISSUE THREAD

**Issue by SYSUykLin** [yuehaowang/bilarf#2]
Hello:
    Great work! I have two questions for your code:
    (1)  In code of the "Model forward()", I found an "exposure_idx" attribute, Did you use this variable in your experiments?
![image](https://github.com/yuehaowang/bilarf/assets/34080744/54eaf845-97c5-4a5a-94a3-7c82b3756451)
    (2) Use a 3D Bilateral Grid during the training stage, and disable the 3D Bilateral Grid during the eval stage, is that correct? 

Thanks!!

**Comment by yuehaowang** [comment]
Hi, thanks for your questions!

1. The `exposure_idx` is used for the RawNeRF setting, which is originally included in the [zipnerf-pytorch](https://github.com/SuLvXiangXin/zipnerf-pytorch) codebase. While our method does not use it.
2. In the eval stage, I think we have to disable the 3D bilateral grid as we don't have them for test views. The evaluation is borrowed from previous papers (RawNeRF, MipNeRF): In the training stage, per-view exposure/GLO will be optimized. In the eval stage, GLO vectors/exposure values are set to uniform values, and color-corrected metrics are used to reflect photometric distances.

**Comment by SYSUykLin** [comment]
> Hi, thanks for your questions!
> 
> 1. The `exposure_idx` is used for the RawNeRF setting, which is originally included in the [zipnerf-pytorch](https://github.com/SuLvXiangXin/zipnerf-pytorch) codebase. While our method does not use it.
> 2. In the eval stage, I think we have to disable the 3D bilateral grid as we don't have them for test views. The evaluation is borrowed from previous papers (RawNeRF, MipNeRF-360): In the training stage, per-view exposure/GLO will be optimized. In the eval stage, GLO vectors/exposure values are set to uniform values, and color-corrected metrics are used to reflect photometric distances.

Thanks for your reply.  But I found that "num_glo_features" variables in your "model.py” sets to zero, sound like u did not use this varibles. And Also, I did not find the setting for this variable "num_glo_features" in any other *.gin files. Thanks

**Comment by yuehaowang** [comment]
Sorry for misleading you.
I mean the use of 3D bilateral grids is like GLO vectors'. The per-view 3D bilateral grids will be optimized during the training stage and set to identity transforms (equivalent to disabled) during the eval stage. Not to say GLO vectors are used in our method.

**Comment by SYSUykLin** [comment]
Thanks for your reply, thank you very much
