### ISSUE TITLE
about decouple ISP enhancement

### ISSUE THREAD

**Issue by LuXiao0228** [yuehaowang/bilarf#4]
Hello,

I have a small query regarding your outstanding article and would greatly appreciate your guidance.

In the paper, you mention the use of a bilateral grid to "decouple ISP enhancement" while simultaneously reconstructing the radiance field without the camera's ISP enhancement, wouldn't this approach result in an image that resembles the greenish raw output from the camera sensor? However, it appears that the paper does not reconstruct the radiance field without ISP enhancement, as the test results directly compare the rendered views with the corresponding ground truth sRGB.  I would like to know if the description of "decoupling ISP enhancement" in the paper is reasonable? Or is the primary function of the bilateral grid proposed in the paper to learn the enhancement for the inconsistencies across multiple views?

Thank you for your time and assistance.

**Comment by yuehaowang** [comment]
Hi,

Thank you very much for your question!
Yes, "decouple ISP enhancement" refers to disentangling inconsistent ISP enhancement across input views.

Given multi-view images only, inversion of the whole ISP pipeline is unlikely feasible. Our workaround is to inverse part of the ISP. In this way, radiance fields will output renderings with average processing, and per-view bilateral grids will express the specific processing for each view.

**Comment by LuXiao0228** [comment]
Your response has resolved my confusion. Thank you very much for your detailed explanation!
