### ISSUE TITLE
About Recolor

### ISSUE THREAD

**Issue by Xu-Zirui** [yuehaowang/bilarf#5]
Hello，thanks for your work. I have a question about recolor, when i run the recolor demo, the result is so 
strange. like this:
![image](https://github.com/user-attachments/assets/2a5d5c5c-1f5e-4404-afc9-fe3fae4781fe)
And this is my config:
![image](https://github.com/user-attachments/assets/beb7e043-b668-4356-bb38-1916b529722a)
![image](https://github.com/user-attachments/assets/cb377c3a-544d-45be-ae1b-42d4ef83847b)

**Comment by yuehaowang** [comment]
How about modifying `FT_TGT_POSE=path:32` to `FT_TGT_POSE=test:32`? The edited image is a test view, indicated in the filename "edit1_color_***test***_032.jpg".
