### ISSUE TITLE
synthetic data

### ISSUE THREAD

**Issue by Willamare** [yuehaowang/bilarf#7]
Hello, can it be used on synthetic data? If not, what modifications are needed?

**Comment by yuehaowang** [comment]
Hi, 

I think our bilateral guided training can directly work with any data formats supported in the zipnerf-pytorch codebase.

To enable bilateral guided finishing on synthetic data (Blender), you will need to modify the [Blender class](https://github.com/yuehaowang/bilarf/blob/57bbc4023751e24fd65d7128f441a1134a04397f/internal/datasets.py#L479) to load edited views and the corresponding camera poses. You can refer to the code below as a reference:

https://github.com/yuehaowang/bilarf/blob/57bbc4023751e24fd65d7128f441a1134a04397f/internal/datasets.py#L711-L755

**Comment by Willamare** [comment]
Thank you very much for your response.
